theme: jekyll-theme-minimal
title: Niveda Balananthan
description: Just a place where I'll be documenting my journey through ungrad! 
logo: [https://github.com/nivedabala/nivedabala.github.io/blob/master/assets/headshot.jpeg]
show_downloads: ["true"]
