theme: jekyll-theme-minimal
title: Niveda Balananthan
description: Just a place where I'll be documenting my upcoming projects as I learn to code!
image: ![Image](https://github.com/nivedabala/nivedabala.github.io/blob/master/assets/headshot.jpeg)
